
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/MOVIE?characterEncoding=utf8&useSSL=false
    username: cjx913
    password: cjx913
  jpa:
    database: mysql
    show-sql: true
    hibernate:
      ddl-auto: update
      naming:
        strategy: org.hibernate.cfg.ImprovedNamingStrategy

  thymeleaf:
    prefix: /WEB-INF/views/
    suffix: .html
    encoding: UTF-8
    mode: HTML5
    cache: false
    content-type: text/html
server:
  port: 8080